## Importar Librerías

In [4]:
# Librerías básicas
import numpy as np
import pandas as pd

# Librerías de procesamiento
from sklearn.preprocessing import MinMaxScaler

# Librerías del modelo 
from sklearn.ensemble import RandomForestClassifier

# Librerías de entrenamiento
from sklearn.model_selection import train_test_split
from sklearn import metrics 

## Import Dataset

In [5]:
df = pd.read_csv('.\\BankChurn.csv')


In [6]:
df.shape

(10127, 20)

In [7]:
df.head()

Attrition_Flag  Customer_Age Gender  Dependent_count Education_Level  \
0  Existing Customer            45      M                3     High School   
1  Existing Customer            49      F                5        Graduate   
2  Existing Customer            51      M                3        Graduate   
3  Existing Customer            40      F                4     High School   
4  Existing Customer            40      M                3      Uneducated   

  Marital_Status Income_Category Card_Category  Months_on_book  \
0        Married     $60K - $80K          Blue              39   
1         Single  Less than $40K          Blue              44   
2        Married    $80K - $120K          Blue              36   
3        Unknown  Less than $40K          Blue              34   
4        Married     $60K - $80K          Blue              21   

   Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                         5                       1                      3   
1                         6                       1                      2   
2                         4                       1                      0   
3                         3                       4                      1   
4                         5                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000

In [8]:
df["Attrition_Flag"].unique()

array(['Existing Customer', 'Attrited Customer'], dtype=object)

In [9]:
df.groupby(["Attrition_Flag"]).count()

Customer_Age  Gender  Dependent_count  Education_Level  \
Attrition_Flag                                                              
Attrited Customer          1627    1627             1627             1627   
Existing Customer          8500    8500             8500             8500   

                   Marital_Status  Income_Category  Card_Category  \
Attrition_Flag                                                      
Attrited Customer            1627             1627           1627   
Existing Customer            8500             8500           8500   

                   Months_on_book  Total_Relationship_Count  \
Attrition_Flag                                                
Attrited Customer            1627                      1627   
Existing Customer            8500                      8500   

                   Months_Inactive_12_mon  Contacts_Count_12_mon  \
Attrition_Flag                                                     
Attrited Customer                    1627                   1627   
Existing Customer                    8500                   8500   

                   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
Attrition_Flag                                                          
Attrited Customer          1627                 1627             1627   
Existing Customer          8500                 8500             8500   

                   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
Attrition_Flag                                                             
Attrited Customer                  1627             1627            1627   
Existing Customer                  8500             8500            8500   

                   Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
Attrition_Flag                                                 
Attrited Customer                 1627                   1627  
Existing Customer                 8500                   8500

In [10]:
df.describe()

Customer_Age  Dependent_count  Months_on_book  \
count  10127.000000     10127.000000    10127.000000   
mean      46.325960         2.346203       35.928409   
std        8.016814         1.298908        7.986416   
min       26.000000         0.000000       13.000000   
25%       41.000000         1.000000       31.000000   
50%       46.000000         2.000000       36.000000   
75%       52.000000         3.000000       40.000000   
max       73.000000         5.000000       56.000000   

       Total_Relationship_Count  Months_Inactive_12_mon  \
count              10127.000000            10127.000000   
mean                   3.812580                2.341167   
std                    1.554408                1.010622   
min                    1.000000                0.000000   
25%                    3.000000                2.000000   
50%                    4.000000                2.000000   
75%                    5.000000                3.000000   
max                    6.000000                6.000000   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
count           10127.000000  10127.000000         10127.000000   
mean                2.455317   8631.953698          1162.814061   
std                 1.106225   9088.776650           814.987335   
min                 0.000000   1438.300000             0.000000   
25%                 2.000000   2555.000000           359.000000   
50%                 2.000000   4549.000000          1276.000000   
75%                 3.000000  11067.500000          1784.000000   
max                 6.000000  34516.000000          2517.000000   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
count     10127.000000          10127.000000     10127.000000    10127.000000   
mean       7469.139637              0.759941      4404.086304       64.858695   
std        9090.685324              0.219207      3397.129254       23.472570   
min           3.000000              0.000000       510.000000       10.000000   
25%        1324.500000              0.631000      2155.500000       45.000000   
50%        3474.000000              0.736000      3899.000000       67.000000   
75%        9859.000000              0.859000      4741.000000       81.000000   
max       34516.000000              3.397000     18484.000000      139.000000   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
count         10127.000000           10127.000000  
mean              0.712222               0.274894  
std               0.238086               0.275691  
min               0.000000               0.000000  
25%               0.582000               0.023000  
50%               0.702000               0.176000  
75%               0.818000               0.503000  
max               3.714000               0.999000

In [11]:
# number of churn and non-churn 
counts = df.Attrition_Flag.value_counts()
perc_churn = (counts[1] / (counts[0] + counts[1])) * 100

# no. of duplicates 
duplicates = len(df[df.duplicated()])

# no of missing values
missing_values = df.isnull().sum().sum()

# Data types in dataset
types = df.dtypes.value_counts()

In [12]:
print("Churn Rate = %.1f %%"%(perc_churn))
print('Number of Duplicate Entries: %d'%(duplicates))
print('Number of Missing Values: %d'%(missing_values))
print('Number of Features: %d'%(df.shape[1]))
print('Number of Customers: %d'%(df.shape[0]))
print('Data Types and Frequency in Dataset:')
print(types)

Churn Rate = 16.1 %
Number of Duplicate Entries: 0
Number of Missing Values: 0
Number of Features: 20
Number of Customers: 10127
Data Types and Frequency in Dataset:
int64      9
object     6
float64    5
dtype: int64


## Pre-Processing

In [13]:
# make gender and outcome numerical
df['Gender'] = df['Gender'].map({'M': 1, 'F': 0})
df['Attrition_Flag'] = df['Attrition_Flag'].map({'Attrited Customer': 1, 'Existing Customer': 0})


# Code adapted from: https://www.kaggle.com/code/andreshg/churn-prediction-0-99-auc-h2o-sklearn-smote#2.-Feature-Engeneering
catcols = df.select_dtypes(exclude = ['int64','float64']).columns
intcols = df.select_dtypes(include = ['int64']).columns
floatcols = df.select_dtypes(include = ['float64']).columns

# one-hot encoding on categorical columns
df = pd.get_dummies(df, columns = catcols)

# minmax scaling numeric features 
for col in df[floatcols]:
    df[col] = MinMaxScaler().fit_transform(df[[col]])
    
for col in df[intcols]:
    df[col] = MinMaxScaler().fit_transform(df[[col]])
    
print('New Number of Features: %d'%(df.shape[1]))  

New Number of Features: 37


In [14]:
# split into X and y
X = df.drop('Attrition_Flag', axis = 1)
y = df['Attrition_Flag']

In [15]:
display(X)

Customer_Age  Gender  Dependent_count  Months_on_book  \
0          0.404255     1.0              0.6        0.604651   
1          0.489362     0.0              1.0        0.720930   
2          0.531915     1.0              0.6        0.534884   
3          0.297872     0.0              0.8        0.488372   
4          0.297872     1.0              0.6        0.186047   
...             ...     ...              ...             ...   
10122      0.510638     1.0              0.4        0.627907   
10123      0.319149     1.0              0.4        0.279070   
10124      0.382979     0.0              0.2        0.534884   
10125      0.085106     1.0              0.4        0.534884   
10126      0.361702     0.0              0.4        0.279070   

       Total_Relationship_Count  Months_Inactive_12_mon  \
0                           0.8                0.166667   
1                           1.0                0.166667   
2                           0.6                0.166667   
3                           0.4                0.666667   
4                           0.8                0.166667   
...                         ...                     ...   
10122                       0.4                0.333333   
10123                       0.6                0.333333   
10124                       0.8                0.500000   
10125                       0.6                0.500000   
10126                       1.0                0.333333   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                   0.500000      0.340190             0.308701   
1                   0.333333      0.206112             0.343266   
2                   0.000000      0.059850             0.000000   
3                   0.166667      0.056676             1.000000   
4                   0.000000      0.099091             0.000000   
...                      ...           ...                  ...   
10122               0.500000      0.077536             0.735399   
10123               0.500000      0.085819             0.868494   
10124               0.666667      0.120042             0.000000   
10125               0.500000      0.116172             0.000000   
10126               0.666667      0.270566             0.779102   

       Avg_Open_To_Buy  ...  Income_Category_$120K +  \
0             0.345116  ...                        0   
1             0.214093  ...                        0   
2             0.098948  ...                        0   
3             0.022977  ...                        0   
4             0.136557  ...                        0   
...                ...  ...                      ...   
10122         0.062266  ...                        0   
10123         0.060499  ...                        0   
10124         0.156637  ...                        0   
10125         0.152928  ...                        0   
10126         0.244082  ...                        0   

       Income_Category_$40K - $60K  Income_Category_$60K - $80K  \
0                                0                            1   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            1   
...                            ...                          ...   
10122                            1                            0   
10123                            1                            0   
10124                            0                            0   
10125                            1                            0   
10126                            0                            0   

       Income_Category_$80K - $120K  Income_Category_Less than $40K  \
0                                 0                               0   
1                                 0                               1   
2                                

## Feature Selection

In [16]:
# the selected variables
FEATURES = [
    'Customer_Age', 
    'Total_Amt_Chng_Q4_Q1', 
    'Total_Relationship_Count', 
    'Total_Revolving_Bal', 
    'Total_Ct_Chng_Q4_Q1', 
    'Total_Trans_Ct', 
    'Total_Trans_Amt', 
    'Months_Inactive_12_mon', 
    'Contacts_Count_12_mon'
    ]


## Apply final model

In [17]:
forest = RandomForestClassifier(n_estimators = 850, max_depth = 19, random_state = 1200)

In [18]:
X_new = X[FEATURES]

train_x, test_x, train_y, test_y = train_test_split(X_new, y, test_size = 0.25, random_state = 42)
    
forest.fit(train_x,train_y)
forest.score(test_x, test_y)
pred_test = forest.predict(test_x)
    
f1 = metrics.f1_score(test_y, pred_test)
test_acc = metrics.accuracy_score(test_y, pred_test)
con = metrics.confusion_matrix(test_y, pred_test)
precision = metrics.precision_score(test_y, pred_test)
recall = metrics.recall_score(test_y, pred_test)
roc = metrics.roc_auc_score(test_y, pred_test)

In [25]:
pred_test[0]

0.0

In [27]:
type(pred_test[0])

numpy.float64

In [19]:
print('Accuracy Score', test_acc)
print('Precision', precision)
print('Recall', recall)
print('F1-Score', f1)
print('ROC Score', roc)
print(con)

Accuracy Score 0.9664296998420221
Precision 0.9304123711340206
Recall 0.8615751789976134
F1-Score 0.8946716232961587
ROC Score 0.9243985691485936
[[2086   27]
 [  58  361]]


In [20]:
#cross validation
from sklearn.model_selection import cross_validate 

cv_results = cross_validate(forest, X_new, y, scoring = ('f1', 'accuracy', 'roc_auc'), cv = 8)
sorted(cv_results.keys())

['fit_time', 'score_time', 'test_accuracy', 'test_f1', 'test_roc_auc']

In [21]:
cv_results['test_roc_auc'] 

array([0.91056078, 0.96866615, 0.98541168, 0.9918462 , 0.99539807,
       0.99796213, 0.8989536 , 0.90523967])

In [22]:
cv_results['test_f1'] 

array([0.60892388, 0.82324455, 0.89047619, 0.8814433 , 0.89189189,
       0.921875  , 0.78450363, 0.74285714])

In [23]:
cv_results['test_accuracy'] 

array([0.88230648, 0.94233807, 0.96366509, 0.96366509, 0.96840442,
       0.97630332, 0.92969984, 0.92885375])